Print usage when missing arguments

diff --git a/libexec/hr-clone b/libexec/hr-clone
--- a/libexec/hr-clone
+++ b/libexec/hr-clone
@@ -20,7 +20,11 @@ if [ "$1" = "--complete" ]; then
 fi
 
 if [ -z "$1" ]; then
-  echo "Error: please provide a a repo" >&2
+  {
+    hr-help clone
+    echo
+    echo "ERROR: please provide a a repo"
+  } >&2
   exit 1
 fi
 
diff --git a/libexec/hr-hinder b/libexec/hr-hinder
--- a/libexec/hr-hinder
+++ b/libexec/hr-hinder
@@ -13,9 +13,11 @@ set -e
 ip=$1
 
 if [ -z "$ip" ]; then
-  hr-help hinder
-  echo
-  echo "ERROR: You must provide a network address or 'reset'" >&2
+  {
+    hr-help hinder
+    echo
+    echo "ERROR: You must provide a network address or 'reset'"
+  } >&2
   exit 1
 fi
 
